soundFiles = []
with open ("src/engine/audio/sound_list.h", "r") as file:
	inEnum = False
	for line in file:
		if "enum" in line:
			inEnum = True
			continue
		if 'NumSounds' in line:
			break
		
		if inEnum:
			if "//" in line or line.isspace() or '{' in line or "Null_Sound" in line:
				continue
			soundFiles.append(line.strip().rstrip(','))

fileStr = """// generated by sound_load.py
#include "sound_list.h"
#include "audio.h"

void KSoundID::LoadSounds()
{
#if !_NOSOUND"""

for file in soundFiles:
	fileStr += "\n\tSoundList[" + file + "] = KAudio::LoadSound(\"" + file.lower() + "\");"

fileStr +="""
#endif
}
"""

with open ("src/engine/audio/sound_load.cpp", "w") as file:
	file.write(fileStr)

print("finished")
	