// generated by sound_load.py
#include "sound_list.h"
#include "audio.h"

void KSoundID::LoadSounds()
{
#if !_NOSOUND
	SoundList[Player_Jump] = KAudio::LoadSound("player_jump");
	SoundList[Player_Footstep_Generic] = KAudio::LoadSound("player_footstep_generic");
	SoundList[Player_Land_Generic] = KAudio::LoadSound("player_land_generic");
	SoundList[Player_Wall_Bump] = KAudio::LoadSound("player_wall_bump");
	SoundList[Player_Pain_1] = KAudio::LoadSound("player_pain_1");
	SoundList[Player_Pain_2] = KAudio::LoadSound("player_pain_2");
	SoundList[Player_Pain_3] = KAudio::LoadSound("player_pain_3");
	SoundList[Player_Pain_4] = KAudio::LoadSound("player_pain_4");
	SoundList[Player_Death_1] = KAudio::LoadSound("player_death_1");
	SoundList[Player_Death_2] = KAudio::LoadSound("player_death_2");
	SoundList[Player_Step_1] = KAudio::LoadSound("player_step_1");
	SoundList[Player_Step_2] = KAudio::LoadSound("player_step_2");
	SoundList[Player_Step_3] = KAudio::LoadSound("player_step_3");
	SoundList[Player_Spawn] = KAudio::LoadSound("player_spawn");
	SoundList[Fire_Rocket_Primary] = KAudio::LoadSound("fire_rocket_primary");
	SoundList[Fire_Rocket_Alt] = KAudio::LoadSound("fire_rocket_alt");
	SoundList[Fire_Shotgun_Primary] = KAudio::LoadSound("fire_shotgun_primary");
	SoundList[Fire_Shotgun_Alt] = KAudio::LoadSound("fire_shotgun_alt");
	SoundList[Fire_Cannon_Primary] = KAudio::LoadSound("fire_cannon_primary");
	SoundList[Fire_Cannon_Alt] = KAudio::LoadSound("fire_cannon_alt");
	SoundList[Fire_Blaster_Primary] = KAudio::LoadSound("fire_blaster_primary");
	SoundList[Fire_Blaster_Alt] = KAudio::LoadSound("fire_blaster_alt");
	SoundList[Blaster_Frenzy_Loop] = KAudio::LoadSound("blaster_frenzy_loop");
	SoundList[Proj_Rocket_Hum] = KAudio::LoadSound("proj_rocket_hum");
	SoundList[Rocket_Explode_1] = KAudio::LoadSound("rocket_explode_1");
	SoundList[Rocket_Explode_2] = KAudio::LoadSound("rocket_explode_2");
	SoundList[Cannon_Explode_1] = KAudio::LoadSound("cannon_explode_1");
	SoundList[Shard_Hit_1] = KAudio::LoadSound("shard_hit_1");
	SoundList[Shard_Hit_2] = KAudio::LoadSound("shard_hit_2");
	SoundList[Shard_Hit_3] = KAudio::LoadSound("shard_hit_3");
	SoundList[Shard_Hit_4] = KAudio::LoadSound("shard_hit_4");
	SoundList[Ambient_Portal] = KAudio::LoadSound("ambient_portal");
	SoundList[Ambient_Launcher] = KAudio::LoadSound("ambient_launcher");
	SoundList[Invis_On] = KAudio::LoadSound("invis_on");
	SoundList[Invis_Off] = KAudio::LoadSound("invis_off");
	SoundList[Enter_Portal] = KAudio::LoadSound("enter_portal");
	SoundList[Launcher_Launch] = KAudio::LoadSound("launcher_launch");
	SoundList[Pickup_Gun] = KAudio::LoadSound("pickup_gun");
	SoundList[Respawn_Weapon] = KAudio::LoadSound("respawn_weapon");
	SoundList[Health_Respawn] = KAudio::LoadSound("health_respawn");
	SoundList[Respawn_Brain] = KAudio::LoadSound("respawn_brain");
	SoundList[Despawn_Brain] = KAudio::LoadSound("despawn_brain");
	SoundList[Ambient_Brain] = KAudio::LoadSound("ambient_brain");
	SoundList[Carry_Brain] = KAudio::LoadSound("carry_brain");
	SoundList[Drop_Brain] = KAudio::LoadSound("drop_brain");
	SoundList[Despawn_HP_Small] = KAudio::LoadSound("despawn_hp_small");
	SoundList[Despawn_HP_Med] = KAudio::LoadSound("despawn_hp_med");
	SoundList[Despawn_HP_Big] = KAudio::LoadSound("despawn_hp_big");
	SoundList[Respawn_HP_Small] = KAudio::LoadSound("respawn_hp_small");
	SoundList[Respawn_HP_Med] = KAudio::LoadSound("respawn_hp_med");
	SoundList[Respawn_HP_Big] = KAudio::LoadSound("respawn_hp_big");
	SoundList[Ambient_Underwater_Shallow] = KAudio::LoadSound("ambient_underwater_shallow");
	SoundList[Ambient_Underwater_Deep] = KAudio::LoadSound("ambient_underwater_deep");
	SoundList[Menu_Close] = KAudio::LoadSound("menu_close");
	SoundList[Menu_Open] = KAudio::LoadSound("menu_open");
	SoundList[Menu_Scroll] = KAudio::LoadSound("menu_scroll");
	SoundList[Chat_Beep] = KAudio::LoadSound("chat_beep");
	SoundList[Spree_Announce] = KAudio::LoadSound("spree_announce");
	SoundList[Spree_Ended] = KAudio::LoadSound("spree_ended");
	SoundList[Score_Frag] = KAudio::LoadSound("score_frag");
	SoundList[Score_Death] = KAudio::LoadSound("score_death");
	SoundList[Damage_Tick_0] = KAudio::LoadSound("damage_tick_0");
	SoundList[Damage_Tick_1] = KAudio::LoadSound("damage_tick_1");
	SoundList[Damage_Tick_2] = KAudio::LoadSound("damage_tick_2");
	SoundList[Damage_Tick_3] = KAudio::LoadSound("damage_tick_3");
	SoundList[Damage_Tick_4] = KAudio::LoadSound("damage_tick_4");
	SoundList[Damage_Tick_5] = KAudio::LoadSound("damage_tick_5");
	SoundList[Damage_Tick_6] = KAudio::LoadSound("damage_tick_6");
	SoundList[Damage_Tick_7] = KAudio::LoadSound("damage_tick_7");
	SoundList[Damage_Tick_8] = KAudio::LoadSound("damage_tick_8");
	SoundList[Damage_Tick_9] = KAudio::LoadSound("damage_tick_9");
	SoundList[Damage_Tick_10] = KAudio::LoadSound("damage_tick_10");
	SoundList[Damage_Tick_11] = KAudio::LoadSound("damage_tick_11");
#endif
}
